app/student/__init__.py
from flask import Blueprint
student = Blueprint('student', __name__)
# from . import views, errors
from . import views

app/student/views.py
# -*- coding: utf-8 -*-


from flask import render_template, flash,redirect,request, url_for,g,abort
from . import student # student blueprint
from app.models import Student_termin, Predmet, Termin, Student, Student_predmet
from flask.ext.login import logout_user,login_user, login_required,current_user

@student.before_request
@login_required
def before_request():
	g.user = current_user
	s=Student.query.filter_by(user_id=current_user.id).first()
	if  s is None:
		abort(403)
	g.student=current_user.students[0] #prvy student kt je priradeny k userovi

@student.route('/')
@student.route('/index')
def index():	
	return render_template('student/index.html')

#zobrazi vsetky  zapisane predmety
@student.route('/zap_predmety')
def zap_predmety():
	zap_predmety=[]
	for predmet in  g.student.predmety:
		zap_predmety.append(predmet.predmet)

	return render_template('student/zap_predmety.html',
							zap_predmety=zap_predmety)


#zobrazi vypisane terminy z daneho predmetua taktiez ci je 
# prave logged_in user( alebo user_id) na ne prihlaseny a ak hej tak sa tlacitko zmeni na 'odhlasit'
@student.route('/ukaz_terminy/<int:predmet_id>')
def ukaz_terminy(predmet_id):
	p = Predmet.query.filter_by(id=predmet_id).first()
	if p is None:
		abort(404)

	#exams= s.exams
	terminy= Termin.query.filter_by(predmet_id=p.id).order_by('zaciatok_skusky')

	tpl={}
	cnt={}
	for termin in terminy:
		je_prihlaseny = Student_termin.query.filter_by(student_id=g.student.os_cislo,termin_id=termin.id).first()
		if je_prihlaseny is None:
			tpl[termin]=False 
		else:
			tpl[termin]=True
		cnt[termin] = len(termin.prihlaseni_studenti)

	student_predmetu = Student_predmet.query.filter_by(predmet=p,student_id=g.student.os_cislo).first()

	return render_template('student/ukaz_terminy.html',
					terminy=terminy, 
					tpl=tpl,
					cnt=cnt,
					student_predmetu=student_predmetu,
					predmet=p)

# @student.route('/moje_terminy')
# @student_required
# def moje_terminy
# 	terminy=[]
# 	for i in  g.student.st:
# 		terminy.append(i.termin)
# 	return 

app/templates/student/base.html
<!doctype html>
<html>
<head>
  <!-- jquery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ url_for('static', filename = 'js/jquery-1.11.0.js') }}"><\/script>')</script>
  
  <!-- bootstrap -->
  <link href="{{ url_for('static', filename = 'style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}" rel="stylesheet">
  <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>

   <!-- DataTables-->
  <link href="{{ url_for('static', filename = 'css/jquery.dataTables.css') }}" rel="stylesheet">
  <script type="text/javascript" charset="utf8" src="{{ url_for('static', filename = 'js/jquery.dataTables.js')}}"></script>

  <!-- datepicker -->
  <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap-datepicker.js')}}"></script>
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/datepicker3.css')}}">
  
  <script>
    jQuery(document).ready(function($) {

      $('.alert').click(function(){ // hides alerts on click
        $(this).hide();
      });
     
      // highlights actual tab in navbar 
      $('a[href*="'+window.location.pathname+'"]').parent().addClass('active'); 

    $('#example').dataTable( {
      "oLanguage": {
      "sEmptyTable": "Nie su ziadne data na zobrazenie! aaaw :-("
      },
      
      "iDisplayLength": 5,
    
      });

    });
  </script>

  <!-- favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
  type="image/x-icon">
  <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
  type="image/x-icon">

  <title>{{title}}</title>
</head>
<body>

  <nav class="navbar navbar-default ">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >e-Vzdelávanie</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li>
            <a href="{{ url_for('student.index') }}">Home</a>
          </li>
          <li>
            <a href="{{ url_for('student.zap_predmety')}}">
              Zapísané predmety
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.feedback')}}">
              Feedback
            </a>
          </li>
          <li>
            <a href="{{ url_for('auth.logout') }}">
              Logout( {{current_user.login|capitalize}} )
            </a>
          </li>
        </ul>
     </div>
    </div> <!--container fluid  -->
  </nav>
  
 {% for category,message in get_flashed_messages(with_categories=True,category_filter=['success']) %}
    <div class="alert alert-success">
      <a href="#" class="close" data-dismiss="alert">
        &times;
      </a>
      <div class="row">
          {{ message }}
      </div>
    </div>
 {%endfor%}

  {% for category,message in get_flashed_messages(with_categories=True,category_filter=['danger']) %}
    <div class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">
        &times;
      </a>
      <div class="row">
          {{ message }}
      </div>
    </div>
 {%endfor%}

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

app/templates/student/index.html
{% extends "student/base.html" %}
{% block body %}
  <div class="col-sm-offset-2 col-sm-10">
     <h2>Vitaj študent {{g.user.meno|capitalize}} {{g.user.priezvisko|capitalize}} </h2>
  </div>
{% endblock %}

app/templates/student/ukaz_terminy.html
{% extends "student/base.html" %}
{% block body %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#example').dataTable();
  } );
</script>
<h3>Vypísané termíny skúšok pre predmet {{predmet.meno}}</h3>
<h4>Tvoje body za semester: 
	{% if student_predmetu.body_za_semester < predmet.zapocet %}
	<span style="color:red">
		{{student_predmetu.body_za_semester}}	
	</span>
	{%else%}
	<span style="color:green">
		{{student_predmetu.body_za_semester}}	
	</span>
	{%endif%}
</h4>
<h4>Minimum potrebných bodov pre zápočet: {{predmet.zapocet}}</h4>
 	<hr>
      <table class="table table-striped table-bordered" id="example">
		<thead>
		<tr>
			<th>Začiatok skúšky</th>
			<th>Uzávierka prihlasovania</th>
			<th>Stav</th>
			<th>Kapacita</th>
			<th>Miestnosť</th>
			<th>Poznámka</th>
		</tr>
		</thead>
		<tbody>

		{% for termin in terminy %}
	 		<tr>
	 			<td>
		 			{{termin.zaciatok_skusky}}	
	 			</td>
	 			<td>
	 				{{termin.uzavierka_prihlasovania}}
	 			</td>
	 			<td>
	 				{%if tpl[termin]%}
			 				Odhlasit sa 
				 	{%else%}
			 				Prihlasit sa 
			 		{%endif%}
			 	</td>
			 	<td>
						{{cnt[termin]}}/{{termin.kapacita}} 				
	 			</td>
	 			<td>
	 				{{termin.miestnost.meno}}
	 			</td>
	 			<td>
	 				{{termin.poznamka}}
	 			</td>
	 		</tr>
	 	{% endfor %}
	 	</tbody> 
	</table>
{% endblock %}

app/templates/student/zap_predmety.html
{% extends "student/base.html" %}
{% block body %}
<h3 style="  text-align: center;">Zapísané Predmety</h3>
	<hr>
	<ul class='list'>
		{% for predmet in zap_predmety %}
 		<li style="list-style:none">
			<a  style="width:100%" class="btn btn-primary" 
				href="{{url_for('student.ukaz_terminy',predmet_id=predmet.id)}}">
 				{{predmet.meno}}
 			</a>
 		</li>
	 	{% endfor %}
	</ul>
{% endblock %}