app/ucitel/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField,SelectField,validators,FieldList
from wtforms.validators import Required
from app.models import Miestnost
from app import db



#pouzite na tvorbu terminu
class TerminForm(Form):
	#DateField Text field that accepts a datetime.date value in a given format
	#DateTimeField Text field that accepts a datetime.datetime value in a given format
	# miestnost = TextField('miestnost', validators = [Required()])
	zaciatok_skusky_datum = TextField('zaciatok_skusky_datum', validators = [Required()])
	zaciatok_skusky_cas= TextField('zaciatok_skusky_cas', validators = [Required()])
	uzavierka_prihlasovania_datum = TextField('uzavierka_prihlasovania_datum', validators = [Required()])
	uzavierka_prihlasovania_cas = TextField('uzavierka_prihlasovania_cas', validators = [Required()])
	kapacita = TextField('kapacita', validators = [Required()])
	poznamka = TextField('poznamka')
	miestnost = SelectField('miestnost',
                validators=[validators.optional()],
                )




"""
#pouzite na updatovanie jednej znamky 
class ResultForm(Form):
	f1 = SelectField(u'f1',
                validators=[validators.optional()],
                choices=[('A', 'A'),('B', 'B'),('C', 'C'),('D', 'D'),('E', 'E'),('FX', 'FX'),('n/a', 'n/a')])

#pouzite na updatovanie znamok zo skusky
class MultiResultForm(Form):
    selects = FieldList(SelectField(u'Select', 
                                    validators=[validators.optional()],
                                    choices=[('A', 'A'), ('B', 'B'), ('C', 'C'),
                                             ('D', 'D'), ('E', 'E'), ('FX', 'FX'),
                                             ('n/a', 'n/a')]), min_entries=10)
"""

app/ucitel/__init__.py
from flask import Blueprint
ucitel = Blueprint('ucitel', __name__)
# from . import views, errors
from . import views, forms

app/ucitel/views.py
# -*- coding: utf-8 -*-

from flask import render_template, flash,redirect,request, url_for,g,abort,jsonify
from . import ucitel # ucitel blueprint
from forms import TerminForm
from app import db
from app.models import Student_termin, Predmet, Termin,Ucitel_predmetu,Student_predmet, Miestnost
from flask.ext.login import logout_user,login_user, login_required,current_user
from datetime import datetime
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField,SelectField,validators,FieldList
from flask_weasyprint  import HTML, render_pdf

# @ucitel.route('/hello')
# def hello_html():
#     return render_template('ucitel/index.html')

# @ucitel.route('/hello.pdf')
# def hello_pdf():
#     # Make a PDF from another view
#     return render_pdf(url_for('ucitel.hello_html',follow_redirects=True))

# Alternatively, if the PDF does not have a matching HTML page:
@ucitel.route('/termin<int:termin_id>.pdf')
def termin_pdf(termin_id):

	termin = Termin.query.get(termin_id)
	abort(404) if termin is None else False
	

	zoznam=[]
	for student_terminu in termin.prihlaseni_studenti:
	 	sp = Student_predmet.query.filter_by(student=student_terminu.student,predmet=termin.predmet).first()
	 	zoznam.append(sp)

	# Make a PDF straight from HTML in a string.
	html = render_template('ucitel/template_pre_pdf.html',
		prihlaseni_studenti=zoznam)
	return render_pdf(HTML(string=html))

@ucitel.before_request
@login_required
def before_request():
	g.user = current_user

	if Ucitel_predmetu.query.filter_by(user_id=g.user.id).first() is None:
		abort(404)
    # print g.user.up
    # g.ucitel=g.user.up[0] #prvy student kt je priradeny k userovi

@ucitel.route('/')
@ucitel.route('/index')
def index():	
	return render_template('ucitel/index.html')

# @je_ucitel_predmetu(predmet_id)
@ucitel.route('/zabezpecovane_predmety')
def zabezpecovane_predmety():	
	zabezpecovane_predmety=[]
	for predmet in g.user.vyucovane_predmety:
		zabezpecovane_predmety.append(predmet.predmet)
	return render_template('ucitel/zabezpecovane_predmety.html',
		zabezpecovane_predmety=zabezpecovane_predmety)



#zobrazi vypisane terminy z daneho predmetua taktiez ci je 
@ucitel.route('/ukaz_terminy/<int:predmet_id>')
def ukaz_terminy(predmet_id):
	predmet = Predmet.query.filter_by(id=predmet_id).first()
	if predmet is None:
		abort(404)

	terminy= Termin.query.filter_by(predmet_id=predmet.id).order_by('zaciatok_skusky')

	cnt={}
	for termin in terminy:
		cnt[termin] = len(termin.prihlaseni_studenti)


	return render_template('ucitel/ukaz_terminy.html',
					terminy=terminy, 
					cnt=cnt,
					predmet=predmet)

#editovanie terminu
@ucitel.route('/edituj_termin/<int:termin_id>',methods = ['GET', 'POST'])
def edituj_termin(termin_id):
	termin = Termin.query.filter_by(id=termin_id).first()
	if termin is None:
		abort(404)

	form = TerminForm()
	# text pre labely zobrazujuce sa nad inputfieldom
	form.zaciatok_skusky_datum.label.text=u'Začiatok skúšky: dátum'
	form.zaciatok_skusky_datum.data=termin.zaciatok_skusky.strftime("%d/%m/%Y")
	form.zaciatok_skusky_cas.label.text=u'Začiatok skúšky: čas'
	form.zaciatok_skusky_cas.data=termin.zaciatok_skusky.strftime("%I:%M %p")
	form.uzavierka_prihlasovania_datum.label.text=u'Uzávierka prihlasovania: dátum'
	form.uzavierka_prihlasovania_datum.data=termin.uzavierka_prihlasovania.strftime("%d/%m/%Y")
	form.uzavierka_prihlasovania_cas.label.text=u'Uzávierka prihlasovania: čas'
	form.uzavierka_prihlasovania_cas.data=termin.uzavierka_prihlasovania.strftime("%I:%M %p")
	form.miestnost.label.text=u'Miestnosť'
	form.kapacita.label.text=u'Kapacita'
	form.kapacita.data=termin.kapacita
	form.poznamka.label.text=u'Poznámka'
	form.poznamka.data=termin.poznamka

	#pripravene miestnosti pre selectfields
	miestnosti=[]
	for m in Miestnost.query.all():
		miestnosti.append((m.meno,m.meno+", kapacita:"+str(m.kapacita)))
	form.miestnost.choices=miestnosti

	if form.validate_on_submit():
		zaciatok_skusky = form.zaciatok_skusky_datum.data +" "+form.zaciatok_skusky_cas.data
		zaciatok_skusky = datetime.strptime(zaciatok_skusky, '%d/%m/%Y %I:%M %p')
		# print zaciatok_skusky
		uzavierka_prihlasovania = form.uzavierka_prihlasovania_datum.data +" "+form.uzavierka_prihlasovania_cas.data
		uzavierka_prihlasovania = datetime.strptime(uzavierka_prihlasovania, '%d/%m/%Y %I:%M %p')

		if uzavierka_prihlasovania > zaciatok_skusky:
			flash(u'Uzávierka prihlasovania musí byť skôr než začiatok skúšky',category='danger')
			return render_template('ucitel/edituj_termin.html',termin=termin,form=form)
		vybrana_miestnost=Miestnost.query.filter_by(meno=form.miestnost.data).first()
		if int(form.kapacita.data) > vybrana_miestnost.kapacita:
			flash(u'Prekročil si kapacitu danej miestnosti',category='danger')
			return render_template('ucitel/edituj_termin.html',termin=termin,form=form)

		# toto je to iste ako update nizsie
		# termin.miestnost=vybrana_miestnost
		# termin.zaciatok_skusky= zaciatok_skusky
		# termin.uzavierka_prihlasovania=uzavierka_prihlasovania
		# termin.kapacita=int(form.kapacita.data)
		# termin.poznamka=form.poznamka.data

		rows_changed = Termin.query.filter_by(id=termin_id).update(dict(
			miestnost_id=vybrana_miestnost.id,
		zaciatok_skusky= zaciatok_skusky,
		uzavierka_prihlasovania=uzavierka_prihlasovania,
		kapacita=int(form.kapacita.data),
		poznamka=form.poznamka.data
			))
		db.session.commit()
		flash('Úspešne upravená skúška',category='success')
		return redirect(url_for('ucitel.ukaz_terminy',
						predmet_id=termin.predmet.id))

	return render_template('ucitel/edituj_termin.html',
					termin=termin,
					form=form)


@ucitel.route('/vytvor_skusku/<int:predmet_id>', methods = ['GET', 'POST'])
def vytvor_skusku(predmet_id):

	if Ucitel_predmetu.query.filter_by(predmet_id=predmet_id,user=g.user).first() is None:
		flash('Nezabezpecujes tento predmet',category='danger')
		abort(404)

	predmet = Predmet.query.filter_by(id=predmet_id).first()
	if predmet is None:
		abort(404)

	form = TerminForm()
	# text pre labely zobrazujuce sa nad inputfieldom
	form.zaciatok_skusky_datum.label.text='Zaciatok skusky: datum'
	form.zaciatok_skusky_cas.label.text='Zaciatok skusky: cas'
	form.uzavierka_prihlasovania_datum.label.text='Uzavierka prihlasovania: datum'
	form.uzavierka_prihlasovania_cas.label.text='Uzavierka prihlasovania: cas'
	form.kapacita.label.text='Kapacita'
	form.poznamka.label.text='Poznamka'
	form.miestnost.label.text='Miestnost'

	#pripravene miestnosti pre selectfields
	miestnosti=[]
	for m in Miestnost.query.all():
		miestnosti.append((m.meno,m.meno+", kapacita:"+str(m.kapacita)))
	form.miestnost.choices=miestnosti

	if form.validate_on_submit():
		zaciatok_skusky = form.zaciatok_skusky_datum.data +" "+form.zaciatok_skusky_cas.data
		zaciatok_skusky = datetime.strptime(zaciatok_skusky, '%d/%m/%Y %I:%M %p')
		# print  zaciatok_skusky.strftime('%d/%m/%Y %H:%M')
		uzavierka_prihlasovania = form.uzavierka_prihlasovania_datum.data +" "+form.uzavierka_prihlasovania_cas.data
		uzavierka_prihlasovania = datetime.strptime(uzavierka_prihlasovania, '%d/%m/%Y %I:%M %p')

		if uzavierka_prihlasovania > zaciatok_skusky:
			flash('Uzavierka prihlasovania musi byt skor nez zaciatok skusky',category='danger')
			# return redirect(url_for('ucitel.vytvor_skusku',
						# predmet_id=predmet_id))
			return render_template('ucitel/vytvor_skusku.html',form=form)

		vybrana_miestnost=Miestnost.query.filter_by(meno=form.miestnost.data).first()
		if int(form.kapacita.data) > vybrana_miestnost.kapacita:
			flash('Prekrocil si kapacitu danej miestnosti',category='danger')
			# return redirect(url_for('ucitel.vytvor_skusku',
						# predmet_id=predmet_id))
			return render_template('ucitel/vytvor_skusku.html',form=form)


		novy_termin = Termin(
			predmet=predmet,
			zaciatok_skusky= zaciatok_skusky,
			uzavierka_prihlasovania=uzavierka_prihlasovania,
			kapacita=form.kapacita.data,
			poznamka=form.poznamka.data,
			miestnost=vybrana_miestnost
			)

		db.session.add(novy_termin)
		db.session.commit()
		flash('Uspesne vytvorena skuska',category='success')
		return redirect(url_for('ucitel.ukaz_terminy',
						predmet_id=predmet_id))
	return render_template('ucitel/vytvor_skusku.html',form=form)

def ucitel_OK(predmet_id):
	
	#vyucuje prihlaseny ucitel tento predmet?
	up =Ucitel_predmetu.query.filter_by(user_id=g.user.id,predmet_id=predmet_id).first()
	if up is None:
		abort(403)


# @ucitel.route('/_manazuj_predmet_json/<int:predmet_id>', defaults={'zapocet': 'no','termin_id':0}, methods = ['GET', 'POST']) 
@ucitel.route('/_manazuj_predmet_json/<int:predmet_id>/<int:termin_id>/<zapocet>', methods = ['GET', 'POST'])
def _manazuj_predmet_json(predmet_id,termin_id,zapocet):

	predmet = Predmet.query.filter_by(id=predmet_id).first()
	if predmet is None:
		abort(404)

	ucitel_OK(predmet_id)

	studenti_predmetu=predmet.studenti_predmetu
	# print len(studenti_predmetu)

	if zapocet == 'yes':
		studenti_predmetu_so_zapoctom=[]
		for student_predmetu in studenti_predmetu:
			if student_predmetu.body_za_semester >= predmet.zapocet: # ma dost bodov?
				studenti_predmetu_so_zapoctom.append(student_predmetu)
		studenti_predmetu=studenti_predmetu_so_zapoctom

	is_filtered_by_termin=False
	if termin_id != 0:
		studenti_tohto_terminu=[]
		najdeny_termin=None
		for termin in predmet.terminy:
			if termin.id==termin_id:
				najdeny_termin=termin
		abort(404) if najdeny_termin is None else False
			
			# flash('spatna id terminu',category='danger')
			# return render_template('ucitel/manazuj_predmet',
			# 			predmet_id=predmet_id))
		for studentov_termin in najdeny_termin.prihlaseni_studenti:
			studentov_termin.student #ziskam studenta
			sp = Student_predmet.query.filter_by(student=studentov_termin.student, predmet_id=predmet_id).first()
			abort(404) if sp is None else False
			studenti_tohto_terminu.append(sp) 
		studenti_predmetu=studenti_tohto_terminu
		is_filtered_by_termin=True

	
	form =  vytvor_formular_pre_manazovanie_studentov(studenti_predmetu)
	

app/templates/ucitel/base.html
<!doctype html>
<html>
<head>
  <!-- jquery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ url_for('static', filename = 'js/jquery-1.11.0.js') }}"><\/script>')</script>
  
  <!-- bootstrap -->
  <link href="{{ url_for('static', filename = 'style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}" rel="stylesheet">
  <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>

   <!-- DataTables-->
  <link href="{{ url_for('static', filename = 'css/jquery.dataTables.css') }}" rel="stylesheet">
  <script type="text/javascript" charset="utf8" src="{{ url_for('static', filename = 'js/jquery.dataTables.js')}}"></script>

  <!-- datepicker -->
  <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap-datepicker.js')}}"></script>
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/datepicker3.css')}}">
  
  <script>
    jQuery(document).ready(function($) {

      $('.alert').click(function(){ // hides alerts on click
        $(this).hide();
      });
     
      // highlights actual tab in navbar 
      $('a[href*="'+window.location.pathname+'"]').parent().addClass('active'); 

  /*  $('#example').dataTable( {
      "oLanguage": {
      "sEmptyTable": "Nie su ziadne data na zobrazenie! aaaw :-("
      },
      
      // "iDisplayLength": 5,
    
      });*/

    });
  </script>

  <!-- favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
  type="image/x-icon">
  <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
  type="image/x-icon">

  <title>{{title}}</title>
</head>
<body>

  <nav class="navbar navbar-default ">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >e-Vzdelávanie</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li>
            <a href="{{ url_for('ucitel.index') }}">Home</a>
          </li>
          <li>
            <a href="{{ url_for('ucitel.zabezpecovane_predmety')}}">
              Zabezpečované predmety
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.feedback')}}">
              Feedback
            </a>
          </li>
          <li>
            <a href="{{ url_for('auth.logout') }}">
              Logout( {{current_user.login|capitalize}} )
            </a>
          </li>
        </ul>
     </div>
    </div> <!--container fluid  -->
  </nav>
  
 {% for category,message in get_flashed_messages(with_categories=True,category_filter=['success']) %}
    <div class="alert alert-success">
      <a href="#" class="close" data-dismiss="alert">
        &times;
      </a>
      <div class="row">
          {{ message }}
      </div>
    </div>
 {%endfor%}

  {% for category,message in get_flashed_messages(with_categories=True,category_filter=['danger']) %}
    <div class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">
        &times;
      </a>
      <div class="row">
          {{ message }}
      </div>
    </div>
 {%endfor%}

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

app/templates/ucitel/edituj_termin.html
{% extends "ucitel/base.html" %}
{% block body %}
    <!-- CSS a JS pre timepicker -->
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap-timepicker.min.js')}}"></script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap-timepicker.min.css')}}">

    <form method="post">
        {{ form.hidden_tag() }}
            <!-- Zaciatok skusky , datum -->
            <div class="form-group">
                {{form.zaciatok_skusky_datum.label}}
                {{form.zaciatok_skusky_datum(class_='form-control datepicker',
                             placeholder='Sem zadaj dátum začiatku skúšky',
                           **{'data-provide':'datepicker'},
                           )
                }}
            </div>
 
            {% if form.zaciatok_skusky_datum.errors %}
                <ul class="errors">
                    {% for error in form.zaciatok_skusky_datum.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
   
            <!-- Zaciatok skusky , cas -->
            <script type="text/javascript">
            $(function() {
                    $('.timepicker').timepicker();
                });
            </script>

                {{form.zaciatok_skusky_cas.label}}
            <div class="input-group  bootstrap-timepicker">
                {{form.zaciatok_skusky_cas(class_='form-control input-small timepicker',
                             placeholder='Sem zadaj čas začiatku skúšky')}}
                <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
            </div>
 
            {% if form.zaciatok_skusky_cas.errors %}
                <ul class="errors">
                    {% for error in form.zaciatok_skusky_cas.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}


            <!-- uzavierka_prihlasovania_datum -->
            <div class="form-group">
                {{form.uzavierka_prihlasovania_datum.label}}
                {{form.uzavierka_prihlasovania_datum(class_='form-control datepicker',
                             placeholder='Sem zadaj dátum uzávierky prihlasovania',
                           **{'data-provide':'datepicker'}
                           )
                }}
            </div>
 
            {% if form.uzavierka_prihlasovania_datum.errors %}
                <ul class="errors">
                    {% for error in form.uzavierka_prihlasovania_datum.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}


            <!-- uzavierka_prihlasovania_cas -->
            {{form.uzavierka_prihlasovania_cas.label}}
            <div class="input-group form-group bootstrap-timepicker">
                {{form.uzavierka_prihlasovania_cas(class_='form-control input-small timepicker',
                             placeholder='Sem zadaj čas uzávierky prihlasovania')}}
                <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
            </div>
 
            {% if form.uzavierka_prihlasovania_cas.errors %}
                <ul class="errors">
                    {% for error in form.uzavierka_prihlasovania_cas.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        
            <!-- Miestnost -->
            <div class="form-group">
                {{form.miestnost.label}}
                {{form.miestnost(class_='form-control',
                             placeholder='Sem zadaj  miestnosť')
                }}
            </div>
 
            {% if form.miestnost.errors %}
                <ul class="errors">
                    {% for error in form.miestnost.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!-- kapacita -->
            <div class="form-group">
                {{form.kapacita.label}}
                {{form.kapacita(class_='form-control',
                             placeholder='Sem zadaj kapacitu')
                }}
            </div>
 
            {% if form.kapacita.errors %}
                <ul class="errors">
                    {% for error in form.kapacita.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!-- poznamka -->
            <div class="form-group">
                {{form.poznamka.label}}
                {{form.poznamka(class_='form-control',
                             placeholder='Sem zadaj poznámku')
                }}
            </div>
 
            {% if form.poznamka.errors %}
                <ul class="errors">
                    {% for error in form.poznamka.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            
        <button class="btn btn-primary" style="display:table;">Potvrdiť</button>
    </form>
    <script type="text/javascript">
$('.datepicker').datepicker({
    format: "dd/mm/yyyy",
    autoclose: true,
})
</script>

{% endblock %}

app/templates/ucitel/index.html
{% extends "ucitel/base.html" %}

{% block body %}
	<div class="col-sm-offset-2 col-sm-10">
	 <h2>Vitaj učiteľ {{g.user.meno|capitalize}} {{g.user.priezvisko|capitalize}} </h2>
	</div>	
{% endblock %}

app/templates/ucitel/manazuj_predmet_json.html
{% for student_predmetu in studenti_predmetu %}
		 		<tr>
		 			
		 			<td>
			 			{{student_predmetu.student.skupina}}	
		 			</td>
		 			<td>
			 			{{student_predmetu.student.user.priezvisko}} {{student_predmetu.student.user.meno}} 	
		 			</td>
		 			<td>
	           			{{ form['select0_%d'|format(loop.index0)]}}
		 			</td>
		 			
		 			{% if student_predmetu.body_za_semester < predmet.zapocet %}
		 			<td style="color:red">
	                    {{ form['body_za_semester_%d'|format(loop.index0)](size=1)}}			 				
		 			</td>
		 			{%else%}
		 			<td style="color:green">
	                    {{ form['body_za_semester_%d'|format(loop.index0)](size=1)}}			 				
		 			</td>
		 			{%endif%}
		 			
		 				
				 		<td style="background-color: lightblue;">
	                        {{ form['datum1_%d'|format(loop.index0)](size=4)}}
	                    </td>
				 		<td style="background-color: lightblue;">
	                        {{ form['select1_%d'|format(loop.index0)]}}
	                    </td>
	                    <td style="background-color: lightblue;"> 
	                        {{ form['poznamka1_%d'|format(loop.index0)]}}
	                    </td>

				 		<td style="background-color: lightgreen;">
	                        {{ form['datum2_%d'|format(loop.index0)](size=4)}}
	                    </td>
				 		<td style="background-color: lightgreen;">
	                        {{ form['select2_%d'|format(loop.index0)]}}
	                    </td>
				 		<td style="background-color: lightgreen;">
	                        {{ form['poznamka2_%d'|format(loop.index0)]}}
	                    </td>

				 		<td style="background-color: GreenYellow   ;">
	                        {{ form['datum3_%d'|format(loop.index0)](size=4)}}
	                    </td>
				 		<td style="background-color: GreenYellow   ;">
	                        {{ form['select3_%d'|format(loop.index0)]}}
	                    </td>
				 		<td style="background-color: GreenYellow   ;">
	                        {{ form['poznamka3_%d'|format(loop.index0)]}}
	                    </td>	 		
		 		</tr>
		 	{% endfor %}

app/templates/ucitel/template_pre_pdf.html
{% extends "ucitel/base.html" %}
{% block body %}

<style type="text/css">
	.skupina
	{
		width:4px;
	}
	.meno
	{
		width:10px;
	}
	.body
	{
		width:1px;
	}
	.znamka
	{
		width:1px;
	}
	.poznamka
	{
		width:122px;
	}
	tbody{
				/*overflow:hidden; padding: 0px 0px;*/

	}
</style>

<table class="table table-striped table-bordered" id="example">
	<thead>
		<tr style="background-color:black; color:white" >
			<th class="skupina">SKUP</th>
			<th class="meno">MENO</th>
			<th class="body">BOD</th> <!-- za semester -->
			<th class="znamka">FX</th>
			<th class="poznamka"></th>
		</tr>
	</thead>
	<tbody>

	{% for student_predmetu in prihlaseni_studenti %}
 		<tr>
 			<td class="skupina">
	 			{{student_predmetu.student.skupina}}	
 			</td>
 			<td class="meno">
	 			{{student_predmetu.student.user.priezvisko}}
	 			<br>
	 			 {{student_predmetu.student.user.meno}} 	
 			</td>
 			<td class="body">
 				<br>
                {{student_predmetu.body_za_semester}}			 				
	 		</td>
	 		<td class="znamka">
	 		</td>
	 		<td class="poznamka">
	 			{{student_predmetu.datum1.strftime('%-d.%-m')}} - {{student_predmetu.poznamka1}}
	 			<br>
	 			{{student_predmetu.datum2.strftime('%-d.%-m')}} - {{student_predmetu.poznamka2}}
	 			<br>
	 			{{student_predmetu.datum3.strftime('%-d.%-m')}} - {{student_predmetu.poznamka3}}

	 		</td>
 		</tr>
 	{% endfor %}
 	</tbody> 
</table>
{% endblock %}

app/templates/ucitel/ukaz_terminy.html
{% extends "ucitel/base.html" %}
{% block body %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#example').dataTable();
  } );
</script>
<h3>Vypísane termíny skúšok pre predmet {{predmet.meno}}</h3>
 	<hr>
      <table class="table table-striped table-bordered" id="example">
		<thead>
		<tr>
			<th>Zaciatok skusky</th>
			<th>Uzavierka prihlasovania</th>
			<th>Kapacita</th>
			<th>Miestnost</th>
			<th>Poznamka</th>
			<th>Edit</th>
		</tr>
		</thead>
		<tbody>

		{% for termin in terminy %}
	 		<tr>
	 			<td>
		 			{{termin.zaciatok_skusky}}	
	 			</td>
	 			<td>
	 				{{termin.uzavierka_prihlasovania}}
	 			</td>
			 	<td>
						{{cnt[termin]}}/{{termin.kapacita}} 				
	 			</td>
	 			<td>
	 				{{termin.miestnost.meno}}
	 			</td>
	 			<td>
	 				{{termin.poznamka}}
	 			</td>
	 			<td>
	 				<a href="{{url_for('ucitel.edituj_termin',termin_id=termin.id)}}">
						X
					</a>
	 			</td>
	 		</tr>
	 	{% endfor %}
	 	</tbody> 
	</table>

	<hr>

	<a style="width:100%" class="btn btn-primary" href="{{url_for('ucitel.vytvor_skusku',predmet_id=predmet.id)}}">
		vytvor skusku
	</a>

{% endblock %}